name: Run Unit Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checout Code
          uses: actions/checkout@v3
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12.7"
        
        - name: Install uv
          run: |
            pip install uv
        
        - name: Install dependencies
          run: |
            uv venv
            source .venv/bin/activate
            uv add -r requirements.txt
        
        - name: Run tests with coverage report
          run: |
            source .venv/bin/activate
            pytest --cov=src --cov-report=term-missing tests/
        
        - name: Run test with coverage badge
          run: |
            uv add coverage-badge
            coverage run -m pytest
            coverage report
        
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN}}